#!/usr/bin/env python3
"""Generate Codex agent TOML files from the role briefs in workflow/agents/<phase>/*.md.

Writes .codex/agents/<role>.toml (name, description, body as developer_instructions) and the
[agents.<role>] entries in .codex/config.toml that Codex needs to expose them. Edit the brief and
regenerate; never edit the TOML.

    python3 -m skydiscover.synthesize.workflow.adapters.codex.agents <codex_dir>
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Dict, List, Tuple

AGENTS_DIR = Path(__file__).resolve().parents[2] / "agents"

#: Lets the installer recognise a config.toml it owns and may rewrite.
CONFIG_MARKER = "# generated by skydiscover/synthesize/scripts/install.sh --agent codex"
CONFIG_END = "# end of the generated skydiscover section"

#: Substring every generated agent TOML carries (see render()), so the installer prunes only its
#: own stale role files and never a TOML the user wrote.
AGENT_MARKER = "adapters/codex/agents.py"


def _ours(toml_path: Path) -> bool:
    """True if this TOML was generated by us (carries AGENT_MARKER), so it is safe to remove."""
    try:
        return AGENT_MARKER in toml_path.read_text(encoding="utf-8")
    except OSError:
        return False


def _split_frontmatter(text: str) -> Tuple[Dict[str, str], str]:
    """Return (frontmatter, body). Keys are flat; values may be YAML folded scalars (>-/>)."""
    if not text.startswith("---"):
        return {}, text
    lines = text.splitlines()
    try:
        end = next(i for i in range(1, len(lines)) if lines[i].strip() == "---")
    except StopIteration:
        return {}, text

    fm: Dict[str, str] = {}
    key = None
    folded: List[str] = []
    for raw in lines[1:end]:
        if raw and not raw[0].isspace() and ":" in raw:
            if key is not None:
                fm[key] = " ".join(folded).strip()
            key, _, rest = raw.partition(":")
            key = key.strip()
            rest = rest.strip()
            # A folded scalar (>/>-/|) means the value is the indented block below it.
            folded = [] if rest in (">", ">-", "|", "|-") else [rest]
        elif key is not None and raw.strip():
            folded.append(raw.strip())
    if key is not None:
        fm[key] = " ".join(folded).strip()

    return fm, "\n".join(lines[end + 1 :]).strip()


def _toml_multiline(value: str) -> str:
    """Encode as a TOML multi-line basic string.

    The basic form is used rather than the literal one because a brief may itself contain the
    literal delimiter, which cannot be escaped.
    """
    out = value.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    # A trailing quote would run into the closing delimiter.
    if out.endswith('"'):
        out = out[:-1] + '\\"'
    return f'"""\n{out}\n"""'


def _toml_basic(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ") + '"'


def render(brief: Path) -> Tuple[str, str, str]:
    """Return (role_name, description, toml_text) for one brief."""
    fm, body = _split_frontmatter(brief.read_text(encoding="utf-8"))
    name = fm.get("name") or brief.stem
    description = fm.get("description", "")

    lines = [
        "# Generated from skydiscover/synthesize/workflow/agents/%s by"
        % brief.relative_to(AGENTS_DIR).as_posix(),
        "# workflow/adapters/codex/agents.py. Edit the brief, not this file.",
    ]
    lines += [
        "",
        "name = %s" % _toml_basic(name),
        "description = %s" % _toml_basic(description),
        "developer_instructions = %s" % _toml_multiline(body),
        "",
    ]
    return name, description, "\n".join(lines)


def render_config(roles: List[Tuple[str, str]]) -> str:
    """Return the generated section of .codex/config.toml that declares each role.

    Codex ignores the agent files unless they are declared here.
    """
    out = [
        CONFIG_MARKER,
        "# Declares the /skysynth agent roles so Codex exposes them. Paths are relative to this",
        "# file. Regenerate with: bash skydiscover/synthesize/scripts/install.sh --agent codex",
        "#",
        "# Codex reads this only for a TRUSTED project: approve the directory on first launch,",
        '# or add [projects."<abs path>"] trust_level = "trusted" to ~/.codex/config.toml.',
        "",
    ]
    for name, description in roles:
        out += [
            "[agents.%s]" % name,
            'config_file = "agents/%s.toml"' % name,
            "description = %s" % _toml_basic(description),
            "",
        ]
    out.append(CONFIG_END)
    return "\n".join(out) + "\n"


def merge_config(existing: str, section: str) -> str:
    """The user's config.toml with the generated section replaced (or appended); everything the
    user wrote stays. A file that is only an old generated section is replaced whole."""
    if CONFIG_MARKER in existing:
        head, rest = existing.split(CONFIG_MARKER, 1)
        tail = rest.split(CONFIG_END, 1)[1] if CONFIG_END in rest else ""
        existing = head.rstrip() + ("\n" if head.strip() else "") + tail.lstrip("\n")
    if not existing.strip():
        return section
    return existing.rstrip() + "\n\n" + section


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("codex_dir", help="the project's .codex directory")
    ap.add_argument(
        "--no-config",
        action="store_true",
        help="write only agents/, leaving an existing config.toml alone",
    )
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args(argv)

    # One brief per role under agents/<phase>/; agents/README.md documents them and is not a role.
    briefs = sorted(AGENTS_DIR.glob("*/*.md"))
    if not briefs:
        print(f"no role briefs found under {AGENTS_DIR}", file=sys.stderr)
        return 1

    codex_dir = Path(args.codex_dir)
    agents_out = codex_dir / "agents"
    agents_out.mkdir(parents=True, exist_ok=True)

    roles: List[Tuple[str, str]] = []
    for brief in briefs:
        name, description, toml_text = render(brief)
        (agents_out / f"{name}.toml").write_text(toml_text, encoding="utf-8")
        roles.append((name, description))

    # Prune our own role TOMLs whose brief is gone, so a removed role does not linger as a stale
    # agent -- but never a TOML the user authored (one without our marker).
    keep = {n for n, _ in roles}
    for stale in agents_out.glob("*.toml"):
        if stale.stem not in keep and _ours(stale):
            stale.unlink()

    wrote_config = False
    if not args.no_config:
        config = codex_dir / "config.toml"
        # A config.toml the user wrote keeps everything they wrote; our [agents.*] section is
        # merged in between markers (replaced on rerun). --no-config skips this entirely.
        existing = config.read_text(encoding="utf-8") if config.exists() else ""
        config.write_text(merge_config(existing, render_config(roles)), encoding="utf-8")
        wrote_config = True

    if not args.quiet:
        print(f"Wrote {len(roles)} Codex agent definitions to {agents_out}")
        if wrote_config:
            print(f"Declared them in {codex_dir / 'config.toml'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
